service: merkle-tree-api
runtime: custom
env: flex
manual_scaling:
    instances: 1
resources:
    cpu: 1
    memory_gb: 0.5
    disk_size_gb: 10
vpc_access_connector:
    name: projects/reme-wallet-test/locations/europe-west1/connectors/postgres-connector
